
sudo: required

services:
  - docker

language: generic

git:
  submodules: false

before_install:
  - docker build -t kyleam/mlb-rundiff .

script:
  - docker run -it --rm -v $HOME/outputs:/opt/mlb-rundiff/outputs --entrypoint '/bin/sh' kyleam/mlb-rundiff run-tests > tests-output
  - cat tests-output
  - if grep -q "impossible" tests-output; then false; else true; fi
  - docker run -it --rm -v $HOME/outputs:/opt/mlb-rundiff/outputs kyleam/mlb-rundiff outputs/models/rundiff-oneseason_2011-fit.rds

notifications:
  email:
    on_success: never
    on_failure: always
