#!/bin/sh

## Run "guix package" with project-specific values for
## $GUIX_PACKAGE_PATH and --profile.

if [ -d .guix/packages ]; then
    GUIX_PACKAGE_PATH=$PWD/.guix/packages
else
    unset GUIX_PACKAGE_PATH
fi

guix package --profile=$PWD/.guix/profile "$@"
