#!/bin/sh

pytest-3

Rscript --no-save --no-restore --no-site-file --no-init-file \
        -e "'require(testthat); test_dir(\"./lib\")'"

## Check for runaway lag values.
snakemake -j3 --quiet output/lag/lag-combined-1990_2016.csv
lag_max=$(sed 1d output/lag/lag-combined-1990_2016.csv |
              cut -d, -f4 |
              sed "s/-//" |
              sort -rn |
              head -1)

if [ "$lag_max" -gt 6 ]; then
    echo "A lag magnitude of $lag_max should be impossible"
    exit 1
fi
